### ISSUE TITLE
Automation issue

### ISSUE THREAD

**Issue by Kryptedbbkick** [Cryptonian007/Genisys#12]
When I get to the very end I get a red text that states "Automation supports only Windows systems"

**Comment by Jaggzer** [comment]
> When I get to the very end I get a red text that states "Automation supports only Windows systems"

You need to start it via windows console (CMD).

**Comment by Aliebne** [comment]
hi this script just run in windows system ?
i need run in linux (debian)

**Comment by Cryptonian007** [comment]
You can run [Astra](https://github.com/Cryptonian007/Astra.git) tool if you wanna use in windows
