### ISSUE TITLE
Integrate 2FA? And Default Telegram Sessions by Telegram A/c Providers ?

### ISSUE THREAD

**Issue by pavan061994** [Cryptonian007/Genisys#15]
Can you pls work on integrating 2FA in Genisys and work method to get Telegram Sessions by default working that we get from Telegram Accounts Provider?

**Comment by Cryptonian007** [comment]
Yes I'll work on 2FA. But I am not sure about the telegram sessions that acc providers give. Genisys uses telethon and telethon stores acc data in sessions. I don't know whether telethon can work on these sessions or not. Have to test it

**Comment by pavan061994** [comment]
Okay I will wait for this... keep me posted.
