### ISSUE TITLE
Getting this weird error on Adding users by User Id Option.

### ISSUE THREAD

**Issue by pavan061994** [Cryptonian007/Genisys#16]
`   ______           _
  / ____/__  ____  (_)______  _______
 / / __/ _ \/ __ \/ / ___/ / / / ___/
/ /_/ /  __/ / / / (__  ) /_/ (__  )
\____/\___/_/ /_/_/____/\__, /____/
                       /____/

[i] Genisys Adder[ID] V2.5
[i] Author: github.com/Cryptonian007

[i] Getting entities

Traceback (most recent call last):
  File "C:\Users\Administrator\Downloads\Genisys9\addbyid.py", line 74, in <module>
    client.get_participants(target_m, aggressive=True)
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python39\lib\site-packages\telethon\sync.py", line 39, in syncified
    return loop.run_until_complete(coro)
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python39\lib\asyncio\base_events.py", line 642, in run_until_complete
    return future.result()
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python39\lib\site-packages\telethon\client\chats.py", line 466, in get_participants
    return await self.iter_participants(*args, **kwargs).collect()
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python39\lib\site-packages\telethon\requestiter.py", line 113, in collect
    async for message in self:
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python39\lib\site-packages\telethon\requestiter.py", line 74, in __anext__
    if await self._load_next_chunk():
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python39\lib\site-packages\telethon\client\chats.py", line 200, in _load_next_chunk
    results = await self.client(self.requests)
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python39\lib\site-packages\telethon\client\users.py", line 30, in __call__
    return await self._call(self._sender, request, ordered=ordered)
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python39\lib\site-packages\telethon\client\users.py", line 73, in _call
    raise MultiError(exceptions, results, requests)
telethon.errors.common.MultiError: ([FloodWaitError('A wait of 10 seconds is required (caused by GetParticipantsRequest)'), None, FloodWaitError('A wait of 10 seconds is required (caused by GetParticipantsRequest)'), FloodWaitError('A wait of 10 seconds is required (caused by GetParticipantsRequest)'), FloodWaitError('A wait of 10 seconds is required (caused by GetParticipantsRequest)'), None, None, FloodWaitError('A wait of 10 seconds is required (caused by GetParticipantsRequest)'), None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None], [None, <telethon.tl.types.channels.ChannelParticipants object at 0x0000024BB8A9CF40>, None, None, None, <telethon.tl.types.channels.ChannelParticipants object at 0x0000024BB8965EB0>, <telethon.tl.types.channels.ChannelParticipants object at 0x0000024BB8B2E4C0>, None, <telethon.tl.types.channels.ChannelParticipants object at 0x0000024BB89757F0>, <telethon.tl.types.channels.ChannelParticipants object at 0x0000024BB8985EB0>, <telethon.tl.types.channels.ChannelParticipants object at 0x0000024BB8A2AFA0>, <telethon.tl.types.channels.ChannelParticipants object at 0x0000024BB89EE460>, <telethon.tl.types.channels.ChannelParticipants object at 0x0000024BB89B0160>, <telethon.tl.types.channels.ChannelParticipants object at 0x0000024BB8AE6BB0>, <telethon.tl.types.channels.ChannelParticipants object at 0x0000024BB8B39BB0>, <telethon.tl.types.channels.ChannelParticipants object at 0x0000024BB8C57A90>, <telethon.tl.types.channels.ChannelParticipants object at 0x0000024BB8A5EC10>, <telethon.tl.types.channels.ChannelParticipants object at 0x0000024BB8BA4B20>, <telethon.tl.types.channels.ChannelParticipants object at 0x0000024BB8CC8280>, <telethon.tl.types.channels.ChannelParticipants object at 0x0000024BB8BF6B50>, <telethon.tl.types.channels.ChannelParticipants object at 0x0000024BB8BBB520>, <telethon.tl.types.channels.ChannelParticipants object at 0x0000024BB8C816A0>, <telethon.tl.types.channels.ChannelParticipants object at 0x0000024BB8AF2940>, <telethon.tl.types.channels.ChannelParticipants object at 0x0000024BB8A9C9D0>, <telethon.tl.types.channels.ChannelParticipants object at 0x0000024BB8C17BE0>, <telethon.tl.types.channels.ChannelParticipants object at 0x0000024BB8AA1340>], [<telethon.tl.functions.channels.GetParticipantsRequest object at 0x0000024BB8965460>, <telethon.tl.functions.channels.GetParticipantsRequest object at 0x0000024BB89722B0>, <telethon.tl.functions.channels.GetParticipantsRequest object at 0x0000024BB89725E0>, <telethon.tl.functions.channels.GetParticipantsRequest object at 0x0000024BB89726A0>, <telethon.tl.functions.channels.GetParticipantsRequest object at 0x0000024BB8972760>, <telethon.tl.functions.channels.GetParticipantsRequest object at 0x0000024BB8972820>, <telethon.tl.functions.channels.GetParticipantsRequest object at 0x0000024BB89728E0>, <telethon.tl.functions.channels.GetParticipantsRequest object at 0x0000024BB89729A0>, <telethon.tl.functions.channels.GetParticipantsRequest object at 0x0000024BB8972A60>, <telethon.tl.functions.channels.GetParticipantsRequest object at 0x0000024BB8972B20>, <telethon.tl.functions.channels.GetParticipantsRequest object at 0x0000024BB8972BE0>, <telethon.tl.functions.channels.GetParticipantsRequest object at 0x0000024BB8972CA0>, <telethon.tl.functions.channels.GetParticipantsRequest object at 0x0000024BB8972D60>, <telethon.tl.functions.channels.GetParticipantsRequest object at 0x0000024BB8972E20>, <telethon.tl.functions.channels.GetParticipantsRequest object at 0x0000024BB8972EE0>, <telethon.tl.functions.channels.GetParticipantsRequest object at 0x0000024BB8972FA0>, <telethon.tl.functions.channels.GetParticipantsRequest object at 0x0000024BB89740A0>, <telethon.tl.functions.channels.GetParticipantsRequest object at 0x0000024BB8974160>, <telethon.tl.functions.channels.GetParticipantsRequest object at 0x0000024BB8974220>, <telethon.tl.functions.channels.GetParticipantsRequest object at 0x0000024BB89742E0>, <telethon.tl.functions.channels.GetParticipantsRequest object at 0x0000024BB89743A0>, <telethon.tl.functions.channels.GetParticipantsRequest object at 0x0000024BB8974460>, <telethon.tl.functions.channels.GetParticipantsRequest object at 0x0000024BB8974520>, <telethon.tl.functions.channels.GetParticipantsRequest object at 0x0000024BB89745E0>, <telethon.tl.functions.channels.GetParticipantsRequest object at 0x0000024BB89746A0>, <telethon.tl.functions.channels.GetParticipantsRequest object at 0x0000024BB8974760>])

C:\Users\Administrator\Downloads\Genisys9>`

**Comment by Cryptonian007** [comment]
This is flood wait error. Your account is limited because of spam
