### ISSUE TITLE
Help!

### ISSUE THREAD

**Issue by pattycake131** [Cryptonian007/Genisys#18]
When I open scraper.py in cmd it says this 
Traceback (most recent call last):
  File "C:\Users\patri\Downloads\Genisys-main\Genisys-main\scraper.py", line 41, in <module>
    f = open('vars.txt', 'rb')
FileNotFoundError: [Errno 2] No such file or directory: 'vars.txt'

How do I fix this
patrick.tousignat2001@gmail.com

**Comment by Cryptonian007** [comment]
Make sure you have your accounts stored for this purpose. Use `manager.py`
