### ISSUE TITLE
Please Help me regarding this issue 

### ISSUE THREAD

**Issue by sureshak47** [Cryptonian007/Genisys#21]
Traceback (most recent call last):
  File "C:\Users\sures\Desktop\Genisys1\scraper.py", line 84, in <module>
    members = client.get_participants(group, aggressive=True)
  File "C:\Users\sures\Desktop\Genisys1\venv\lib\site-packages\telethon\sync.py", line 39, in syncified
    return loop.run_until_complete(coro)
  File "C:\Python39\lib\asyncio\base_events.py", line 642, in run_until_complete
    return future.result()
  File "C:\Users\sures\Desktop\Genisys1\venv\lib\site-packages\telethon\client\chats.py", line 466, in get_participants
    return await self.iter_participants(*args, **kwargs).collect()
  File "C:\Users\sures\Desktop\Genisys1\venv\lib\site-packages\telethon\requestiter.py", line 113, in collect
    async for message in self:
  File "C:\Users\sures\Desktop\Genisys1\venv\lib\site-packages\telethon\requestiter.py", line 74, in __anext__
    if await self._load_next_chunk():
  File "C:\Users\sures\Desktop\Genisys1\venv\lib\site-packages\telethon\client\chats.py", line 200, in _load_next_chunk
    results = await self.client(self.requests)
  File "C:\Users\sures\Desktop\Genisys1\venv\lib\site-packages\telethon\client\users.py", line 30, in __call__
    return await self._call(self._sender, request, ordered=ordered)
  File "C:\Users\sures\Desktop\Genisys1\venv\lib\site-packages\telethon\client\users.py", line 73, in _call
    raise MultiError(exceptions, results, requests)
telethon.errors.common.MultiError: ([ChatAdminRequiredError('Chat admin privileges are required to do that in the specified chat (for example, to s
end a message in a channel which is not yours), or invalid permissions used for the channel or group (caused by GetParticipantsRequest)'), ChatAdmi
nRequiredError('Chat admin privileges are required to do that in the specified chat (for example, to send a message in a channel which is not yours
), or invalid permissions used for the channel or group (caused by GetParticipantsRequest)'), ChatAdminRequiredError('Chat admin privileges are req
uired to do that in the specified chat (for example, to send a message in a channel which is not yours), or invalid permissions used for the channe
l or group (caused by GetParticipantsRequest)'), ChatAdminRequiredError('Chat admin privileges are required to do that in the specified chat (for e
xample, to send a message in a channel which is not yours), or invalid permissions used for the channel or group (caused by GetParticipantsRequest)
'), ChatAdminRequiredError('Chat admin privileges are required to do that in the specified chat (for example, to send a message in a channel which
is not yours), or invalid permissions used for the channel or group (caused by GetParticipantsRequest)'), ChatAdminRequiredError('Chat admin privil
eges are required to do that in the specified chat (for example, to send a message in a channel which is not yours), or invalid permissions used fo
r the channel or group (caused by GetParticipantsRequest)'), ChatAdminRequiredError('Chat admin privileges are required to do that in the specified
 chat (for example, to send a message in a channel which is not yours), or invalid permissions used for the channel or group (caused by GetParticip
antsRequest)'), ChatAdminRequiredError('Chat admin privileges are required to do that in the specified chat (for example, to send a message in a ch
annel which is not yours), or invalid permissions used for the channel or group (caused by GetParticipantsRequest)'), ChatAdminRequiredError('Chat
admin privileges are required to do that in the specified chat (for example, to send a message in a channel which is not yours), or invalid permiss
ions used for the channel or group (caused by GetParticipantsRequest)'), ChatAdminRequiredError('Chat admin privileges are required to do that in t
he specified chat (for example, to send a message in a channel which is not yours), or invalid permissions used for the channel or group (caused by
 GetParticipantsRequest)'), ChatAdminRequiredError('Chat admin privileges are required to do that in the specified chat (for example, to send a mes
sage in a channel which is not yours), or invalid permissions used for the channel or group (caused by GetParticipantsRequest)'), ChatAdminRequired
Error('Chat admin privileges are required to do that in the specified chat (for example, to send a message in a channel which is not yours), or inv
alid permissions used for the channel or group (caused by GetParticipantsRequest)'), ChatAdminRequiredError('Chat admin privileges are required to
do that in the specified chat (for example, to send a message in a channel which is not yours), or invalid permissions used for the channel or grou
p (caused by GetParticipantsRequest)'), ChatAdminRequiredError('Chat admin privileges are required to do that in the specified chat (for example, t
o send a message in a channel which is not yours), or invalid permissions used for the channel or group (caused by GetParticipantsRequest)'), ChatA
dminRequiredError('Chat admin privileges are required to do that in the specified chat (for example, to send a message in a channel which is not yo
urs), or invalid permissions used for the channel or group (caused by GetParticipantsRequest)'), ChatAdminRequiredError('Chat admin privileges are
required to do that in the specified chat (for example, to send a message in a channel which is not yours), or invalid permissions used for the cha
nnel or group (caused by GetParticipantsRequest)'), ChatAdminRequiredError('Chat admin privileges are required to do that in the specified chat (fo
r example, to send a message in a channel which is not yours), or invalid permissions used for the channel or group (caused by GetParticipantsReque
st)'), ChatAdminRequiredError('Chat admin privileges are required to do that in the specified chat (for example, to send a message in a channel whi
ch is not yours), or invalid permissions used for the channel or group (caused by GetParticipantsRequest)'), ChatAdminRequiredError('Chat admin pri
vileges are required to do that in the specified chat (for example, to send a message in a channel which is not yours), or invalid permissions used
 for the channel or group (caused by GetParticipantsRequest)'), ChatAdminRequiredError('Chat admin privileges are required to do that in the specif
ied chat (for example, to send a message in a channel which is not yours), or invalid permissions used for the channel or group (caused by GetParti
cipantsRequest)'), ChatAdminRequiredError('Chat admin privileges are required to do that in the specified chat (for example, to send a message in a
 channel which is not yours), or invalid permissions used for the channel or group (caused by GetParticipantsRequest)'), ChatAdminRequiredError('Ch
at admin privileges are required to do that in the specified chat (for example, to send a message in a channel which is not yours), or invalid perm
issions used for the channel or group (caused by GetParticipantsRequest)'), ChatAdminRequiredError('Chat admin privileges are required to do that i
n the specified chat (for example, to send a message in a channel which is not yours), or invalid permissions used for the channel or group (caused
 by GetParticipantsRequest)'), ChatAdminRequiredError('Chat admin privileges are required to do that in the specified chat (for example, to send a
message in a channel which is not yours), or invalid permissions used for the channel or group (caused by GetParticipantsRequest)'), ChatAdminRequi
redError('Chat admin privileges are required to do that in the specified chat (for example, to send a message in a channel which is not yours), or
invalid permissions used for the channel or group (caused by GetParticipantsRequest)'), ChatAdminRequiredError('Chat admin privileges are required
to do that in the specified chat (for example, to send a message in a channel which is not yours), or invalid permissions used for the channel or g
roup (caused by GetParticipantsRequest)')], [None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None,
None, None, None, None, None, None, None, None, None], [<telethon.tl.functions.channels.GetParticipantsRequest object at 0x000002A5394CFC10>, <tele
thon.tl.functions.channels.GetParticipantsRequest object at 0x000002A5394CF8B0>, <telethon.tl.functions.channels.GetParticipantsRequest object at 0
x000002A5394DC550>, <telethon.tl.functions.channels.GetParticipantsRequest object at 0x000002A5394DC610>, <telethon.tl.functions.channels.GetPartic
ipantsRequest object at 0x000002A5394DC6D0>, <telethon.tl.functions.channels.GetParticipantsRequest object at 0x000002A5394DC790>, <telethon.tl.fun
ctions.channels.GetParticipantsRequest object at 0x000002A5394DC850>, <telethon.tl.functions.channels.GetParticipantsRequest object at 0x000002A539
4DC910>, <telethon.tl.functions.channels.GetParticipantsRequest object at 0x000002A5394DC9D0>, <telethon.tl.functions.channels.GetParticipantsReque
st object at 0x000002A5394DCA90>, <telethon.tl.functions.channels.GetParticipantsRequest object at 0x000002A5394DCB50>, <telethon.tl.functions.chan
nels.GetParticipantsRequest object at 0x000002A5394DCC10>, <telethon.tl.functions.channels.GetParticipantsRequest object at 0x000002A5394DCCD0>, <t
elethon.tl.functions.channels.GetParticipantsRequest object at 0x000002A5394DCD90>, <telethon.tl.functions.channels.GetParticipantsRequest object a
t 0x000002A5394DCE50>, <telethon.tl.functions.channels.GetParticipantsRequest object at 0x000002A5394DCF10>, <telethon.tl.functions.channels.GetPar
ticipantsRequest object at 0x000002A5394DCFD0>, <telethon.tl.functions.channels.GetParticipantsRequest object at 0x000002A5394DD0D0>, <telethon.tl.
functions.channels.GetParticipantsRequest object at 0x000002A5394DD190>, <telethon.tl.functions.channels.GetParticipantsRequest object at 0x000002A
5394DD250>, <telethon.tl.functions.channels.GetParticipantsRequest object at 0x000002A5394DD310>, <telethon.tl.functions.channels.GetParticipantsRe
quest object at 0x000002A5394DD3D0>, <telethon.tl.functions.channels.GetParticipantsRequest object at 0x000002A5394DD490>, <telethon.tl.functions.c
hannels.GetParticipantsRequest object at 0x000002A5394DD550>, <telethon.tl.functions.channels.GetParticipantsRequest object at 0x000002A5394DD610>,
 <telethon.tl.functions.channels.GetParticipantsRequest object at 0x000002A5394DD6D0>])

**Comment by Cryptonian007** [comment]
It's an API response from telegram. It says that the account you're using have to be an admin of the chat to scrape members. This happens with some accounts. Nothing to do with the tool.
Try scraping with a different account
