### ISSUE TITLE
error in tsadder 

### ISSUE THREAD

**Issue by anwarmohammedali** [Cryptonian007/Genisys#22]
when i run tsadder file it pop us this error . can you help me with that. Thanks

Traceback (most recent call last):
  File "C:\Users\Anu\Downloads\Compressed\Genisys-main\tsadder.py", line 53, in <module>
    with open('target_grp.txt', 'r') as f:
FileNotFoundError: [Errno 2] No such file or directory: 'target_grp.txt'

**Comment by Cryptonian007** [comment]
If you have used scraper.py then make sure that you press enter to exit. At the last step
