### ISSUE TITLE
I am able to only 50 people in my group

### ISSUE THREAD

**Issue by myLikes2** [Cryptonian007/Genisys#31]
I am only able to add 50 people to my group, I am doing the same procedure as per instructed. But the members are not adding in my group. 
I'm getting the console message that message added successfully but the members are still the same as before the adder starts.. 
What will be the problem and what's it solution ??

**Comment by Cryptonian007** [comment]
The account you're using to add members is probably limited. That's why you may see "false positives", i.e. members are getting added, though they are not.
As for the solution, I recommend using a different account for the same. Limits on accounts are generally removed after 24 hours.

**Comment by henry4564** [comment]
@Mylikes2 can you please give me your WhatsApp number so we can talk
