### ISSUE TITLE
 1 acc 50 member

### ISSUE THREAD

**Issue by gibscarter** [Cryptonian007/Genisys#4]
Hey, just wonder why 1 account only limited to +-50 member added?
I tried creating group and it seems like 0/200000 (200k is the limit)

And if i run multiple account at the same times, is it possible that bot added same member and count it as 2?

Thank you for amazing work!

**Comment by Cryptonian007** [comment]
Hi @gibscarter !
I'm very sorry for late response.
This tool can add 50-60 members per account
Anything more than that may lead to API call restriction from Telegram for spamming
*You can actually use multiple accounts at the same time. I mean unlimited :exclamation: CSV file distribution feature is made for that ; each account will add unique members - no overlaps*

Thank You
