### ISSUE TITLE
Error in tsadder.py

### ISSUE THREAD

**Issue by stingyman12** [Cryptonian007/Genisys#7]
Added everything according to how to.txt file
after the countdown, the program oped a NEW windoww which gives this ERROR
Python was not found; run without arguments to install from the Microsoft Store, or disable this shortcut from Settings > Manage App Execution Aliases.

**Comment by Cryptonian007** [comment]
Most probably python isn't in your environment variables. For that I recommend you to follow <a href='https://datatofish.com/add-python-to-windows-path/'>This</a>. If that doesn't work, follow the instruction. Run python without arguments in command prompt.

**Comment by saif770** [comment]
WAIT THIS TOOL IS WORK INTO WINDOWS OR NDROID @Cryptonian007

**Comment by Cryptonian007** [comment]
@saif770 windows...i may release a new one that is cross platform

**Comment by stingyman12** [comment]
@Cryptonian007  
Disabling python in app execution aliases worked!
But now i get this error after the program opened new window in the place of the above one (right after i get genysis text in that new window)


Traceback (most recent call last):
  File "C:\Users\srira\AppData\Local\Programs\Python\Python39\Genisys-main\addbyid.py", line 85, in <module>
    client(InviteToChannelRequest(entity, lol))
  File "C:\Users\srira\AppData\Local\Programs\Python\Python39\lib\site-packages\telethon\sync.py", line 39, in syncified
    return loop.run_until_complete(coro)
  File "C:\Users\srira\AppData\Local\Programs\Python\Python39\lib\asyncio\base_events.py", line 642, in run_until_complete
    return future.result()
  File "C:\Users\srira\AppData\Local\Programs\Python\Python39\lib\site-packages\telethon\client\users.py", line 30, in __call__
    return await self._call(self._sender, request, ordered=ordered)
  File "C:\Users\srira\AppData\Local\Programs\Python\Python39\lib\site-packages\telethon\client\users.py", line 77, in _call
    result = await future
telethon.errors.rpcerrorlist.ChatAdminRequiredError: Chat admin privileges are required to do that in the specified chat (for example, to send a message in a channel which is not yours), or invalid permissions used for the channel or group (caused by InviteToChannelRequest)

**Comment by Cryptonian007** [comment]
This is an issue while invoking API call. The user must be an admin in order to add members. The same error may not occur with all users.

**Comment by kenxs33** [comment]
@Cryptonian007
Traceback (most recent call last):
  File "tsadder.py", line 118, in <module>
    username = client.get_entity(group)
  File "C:\Users\King\AppData\Roaming\Python\Python38\site-packages\telethon\syn
c.py", line 39, in syncified
    return loop.run_until_complete(coro)
  File "C:\Program Files\Python38\lib\asyncio\base_events.py", line 616, in run_
until_complete
    return future.result()
  File "C:\Users\King\AppData\Roaming\Python\Python38\site-packages\telethon\cli
ent\users.py", line 311, in get_entity
    result.append(await self._get_entity_from_string(x))
  File "C:\Users\King\AppData\Roaming\Python\Python38\site-packages\telethon\cli
ent\users.py", line 525, in _get_entity_from_string
    result = await self(
  File "C:\Users\King\AppData\Roaming\Python\Python38\site-packages\telethon\cli
ent\users.py", line 30, in __call__
    return await self._call(self._sender, request, ordered=ordered)
  File "C:\Users\King\AppData\Roaming\Python\Python38\site-packages\telethon\cli
ent\users.py", line 78, in _call
    self.session.process_entities(result)
  File "C:\Users\King\AppData\Roaming\Python\Python38\site-packages\telethon\ses
sions\sqlite.py", line 281, in process_entities
    c.executemany(
sqlite3.OperationalError: table entities has 6 columns but 5 values were supplie
d

**Comment by stingyman12** [comment]
@Cryptonian007 
the account from which i am trying to add is a admin

**Comment by kenxs33** [comment]
The method of adding members can be changed to No.1 sessions add no.1-10 members, and then to No.2 sessions add no.11-20 members. If there are 10 accounts running in such a single thread, will the speed of add be improved, and will the probability of being ban be reduced

**Comment by stingyman12** [comment]
I want to try that but suddenly when I open tsadder.py it opens and crashes in a second 
thanks for the response 
any way to fix this??

**Comment by Cryptonian007** [comment]
What is the error did you get? Btw I may release a script in the upcoming days that'll be better than this. So stay tuned

**Comment by Cryptonian007** [comment]
@kenxs33 The new script I'm working on satisfies your suggestion

**Comment by stingyman12** [comment]
@Cryptonian007 
thank you I will be waiting...
Also

> What is error did you get? Btw I may release a script in the upcoming days that'll be better than this. So stay tuned

it's not showing anything 
i double click on tsadder.py it opens cmd and within 1-2s it auto closes itself

**Comment by Cryptonian007** [comment]
Run tsadder on CMD.
`python tsadder.py`

**Comment by saif770** [comment]
@Cryptonian007 WILL IT WORK ON ANDROID

**Comment by Flipcashnl** [comment]
Script is running fine and stating members added succesfully. But the group is not filled with users

**Comment by stingyman12** [comment]
> python tsadder.py

getting this error NOW
Python was not found; run without arguments to install from the Microsoft Store, or disable this shortcut from Settings > Manage App Execution Aliases.


> Most probably python isn't in your environment variables. For that I recommend you to follow [This](https://datatofish.com/add-python-to-windows-path/). If that doesn't work, follow the instruction. Run python without arguments in command prompt.

Also tried this but still no LUCK

**Comment by Cryptonian007** [comment]
@stingyman12 the error says everything. It's not able to decode data in csv file. Try scraping from other group

**Comment by Cryptonian007** [comment]
> Script is running fine and stating members added succesfully. But the group is not filled with users

probably your account is limited by Telegram due to spam...try with other accounts
