### ISSUE TITLE
PEER_FLOOD

### ISSUE THREAD

**Issue by cutelake123321** [Cryptonian007/Genisys#9]
hi i'm having the peer_flood program
use 10 different accounts and it's still the same, how to fix this error? I see that you can add but not me, I am in 10 different accounts, they are all group admin and this error, how to fix this? what should be done?

**Comment by Cryptonian007** [comment]
peer flood error is due to spam. If you make too many requests(for example: InviteRequest), Telegram may temporarily limit the account [or ban it, if this still persists]. Not an issue with the tool
